#!/usr/bin/env python

from __future__ import print_function

import os
import glob
import json
import subprocess
import argparse

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk


class CadmiumWindow(Gtk.Window):

    def __init__(self, profiles, url):
        Gtk.Window.__init__(self, title="Cadmium")
        self.profiles = profiles
        self.url = url
        self.set_border_width(10)

        vbox = Gtk.VBox(spacing=6)
        self.add(vbox)

        for profile in self.profiles:
            button = Gtk.Button.new_with_label(profile)
            button.connect("clicked", self.click_profile_button)
            vbox.pack_start(button, True, True, 0)

        button = Gtk.Button.new_with_label("Incognito")
        button.connect("clicked", self.click_incognito_button)
        vbox.pack_start(button, True, True, 0)

    def click_profile_button(self, button):
        button_label = button.get_label()
        self.run_chrome(button_label, ["--profile-directory={0}".format(self.profiles[button_label])])

    def click_incognito_button(self, button):
        self.run_chrome('Incognito', ['--incognito'])

    def run_chrome(self, profile_name, params=[]):
        if self.url:
            params.append(self.url)
        cmd = ['google-chrome'] + params
        print("Starting Chrome with '{0}' profile: {1}".format(profile_name, cmd))
        subprocess.call(cmd)
        Gtk.main_quit()


def cadmium():
    parser = argparse.ArgumentParser()
    parser.add_argument('url', nargs='?', help='The URL to open in Chrome')
    args = parser.parse_args()

    profiles = {}
    for profile_preferences in glob.glob(os.path.expanduser('~/.config/google-chrome/*/Preferences')):
        (profile_path, _) = os.path.split(profile_preferences)
        (_, profile_directory) = os.path.split(profile_path)
        if profile_directory == 'System Profile':
            continue
        with open(profile_preferences, 'r') as preferences_file:
            preferences = json.load(preferences_file)
            profiles[preferences['profile']['name']] = profile_directory

    cwin = CadmiumWindow(profiles, args.url)
    cwin.connect("delete-event", Gtk.main_quit)
    cwin.show_all()
    Gtk.main()

if __name__ == '__main__':
    cadmium()
